### ISSUE TITLE
Baseline, hand-crafted features shot classifier

### ISSUE THREAD

**Issue by tyiannak** [tyiannak/multimodal_movie_analysis#24]

**Comment by apoman38** [comment]
Steps to create the dataset:
1) Download shots and extract them
2) Create 2 folders (static, non_static)
3) Move all shots to folders (2 times one per folder)
4)Run the script [create_dataset.py](https://github.com/tyiannak/multimodal_movie_analysis/blob/Baseline%2C-hand-crafted-features-shot-classifier-%2324/analyze_visual/classification/create_dataset.py)

PS The script creates 2 different csv files. The first contains static shots that have 100 confidence and have been annotated by at least 2 annotators. The second contains non-statics shots that gave 100 confidence, have been annotated by at least 2 annotators.

**Comment by tyiannak** [comment]
It is not productive to ask the user of create_dataset to download the data and duplicate them into 2 folders and then the script will delete the respective files from each folder. What create_dataset.py should do: 
 - read the aggregations (from issue 20, this needs to be common and not have duplicate code).

**Comment by tyiannak** [comment]
@apoman38 checkout the latest commits that fix the bugs on loading/saving the npy feature files.

Please add the following before proceeding to PR:
 - more classifiers (add adaboost, extratrees, randomforests).
 - add classifier params (e.g. C and kernel types in SVM - must use rbf as well!)
 - plot overall confusion matrix at each validation and training result

**Comment by apoman38** [comment]
Three more classifiers (Adaboost, Extratrees, RandomForest) were added to the train.py code. Hyperparameter tuning was performed to find the parameters that give the best results in each algorithm separately. In addition, the confusion matrix is stored as an image for each algorithm separately.
