### ISSUE TITLE
Average agreement calculation

### ISSUE THREAD

**Issue by sofiaele** [tyiannak/multimodal_movie_analysis#49]
https://github.com/tyiannak/multimodal_movie_analysis/blob/d0c2579efddc3fb574db6df94456beee730fb8b6/annotation/aggregate_annotations.py#L177   

Instead of ann_gr_2['Confidence'], print ann_gr['Confidence'], in order for the average agreement to be computed on all samples with 'Number_annotations' >= annotators. Not only on the samples that have 2 annotations.

**Comment by tyiannak** [comment]
Thanx @sofiaele this has been changed in lastest commit
